//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHIETBI_TRANGTHAI
    {
        public int ID { get; set; }
        public string MaLoaiTB { get; set; }
        public string MaTrangThai { get; set; }
    
        public virtual LOAITHIETBI LOAITHIETBI { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
    }
}
