//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYTINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAYTINH()
        {
            this.THIETBIs = new HashSet<THIETBI>();
        }
    
        public string MaMT { get; set; }
        public string IP { get; set; }
        public string MSCum { get; set; }
        public string MAC { get; set; }
        public string TenMT { get; set; }
        public string ProductID { get; set; }
        public Nullable<System.DateTime> ThoiCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual CUM CUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THIETBI> THIETBIs { get; set; }
    }
}
