//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProcessMonitorEntities : DbContext
    {
        public ProcessMonitorEntities()
            : base("name=ProcessMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUM> CUMs { get; set; }
        public virtual DbSet<DanhMucThietBi> DanhMucThietBis { get; set; }
        public virtual DbSet<Head> Heads { get; set; }
        public virtual DbSet<LICHSU> LICHSUs { get; set; }
        public virtual DbSet<LoaiKetNoi> LoaiKetNois { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBIs { get; set; }
        public virtual DbSet<LOAITHIETBI_TRANGTHAI> LOAITHIETBI_TRANGTHAI { get; set; }
        public virtual DbSet<MAYTINH> MAYTINHs { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
        public virtual DbSet<TRAM> TRAMs { get; set; }
        public virtual DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
        public virtual DbSet<TRANGTHAITB> TRANGTHAITBs { get; set; }
    
        public virtual ObjectResult<GetThongTinLichSuTrangThaiThietBi_Result> GetThongTinLichSuTrangThaiThietBi(string maMT)
        {
            var maMTParameter = maMT != null ?
                new ObjectParameter("MaMT", maMT) :
                new ObjectParameter("MaMT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinLichSuTrangThaiThietBi_Result>("GetThongTinLichSuTrangThaiThietBi", maMTParameter);
        }
    
        public virtual ObjectResult<GetThongTinTrangThaiChiTietCuaThietBi_Result> GetThongTinTrangThaiChiTietCuaThietBi(string maTB)
        {
            var maTBParameter = maTB != null ?
                new ObjectParameter("MaTB", maTB) :
                new ObjectParameter("MaTB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTrangThaiChiTietCuaThietBi_Result>("GetThongTinTrangThaiChiTietCuaThietBi", maTBParameter);
        }
    
        public virtual ObjectResult<GetThongTinTrangThaiThietBi_Result> GetThongTinTrangThaiThietBi(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTrangThaiThietBi_Result>("GetThongTinTrangThaiThietBi", mSCumParameter);
        }
    
        public virtual ObjectResult<sp_Search_Result> sp_Search(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_Result>("sp_Search", keywordParameter);
        }
    
        public virtual int sp_SYNC_UpdateTRANGTHAITBTable(Nullable<int> iD, string mATB, Nullable<System.DateTime> tHOIGIAN, string mOTA, Nullable<double> tRANGTHAI, string mATRANGTHAI)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mATBParameter = mATB != null ?
                new ObjectParameter("MATB", mATB) :
                new ObjectParameter("MATB", typeof(string));
    
            var tHOIGIANParameter = tHOIGIAN.HasValue ?
                new ObjectParameter("THOIGIAN", tHOIGIAN) :
                new ObjectParameter("THOIGIAN", typeof(System.DateTime));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(double));
    
            var mATRANGTHAIParameter = mATRANGTHAI != null ?
                new ObjectParameter("MATRANGTHAI", mATRANGTHAI) :
                new ObjectParameter("MATRANGTHAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SYNC_UpdateTRANGTHAITBTable", iDParameter, mATBParameter, tHOIGIANParameter, mOTAParameter, tRANGTHAIParameter, mATRANGTHAIParameter);
        }
    }
}
