//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIETBI()
        {
            this.TRANGTHAITBs = new HashSet<TRANGTHAITB>();
        }
    
        public string MaTB { get; set; }
        public string TenRutGon { get; set; }
        public string TenTB { get; set; }
        public string MaLoaiTB { get; set; }
        public string MaMT { get; set; }
        public string IP { get; set; }
        public string ProductID { get; set; }
        public string MaLoaiKetNoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string ViTri { get; set; }
        public string MaHead { get; set; }
    
        public virtual Head Head { get; set; }
        public virtual LoaiKetNoi LoaiKetNoi { get; set; }
        public virtual LOAITHIETBI LOAITHIETBI { get; set; }
        public virtual MAYTINH MAYTINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHAITB> TRANGTHAITBs { get; set; }
    }
}
